### PR TITLE
Migrate diagnostics from pt-diagnostics to pi-top CLI

### PR DESCRIPTION
**Pull request by m-roberts**
### For now
```
pi-top support {docs} --> pi-top support links {docs} 
pi-top support health_check
```

* Header
	* Shows pt-diagnostics version, if installed via package
	* Shows timestamp
* OS
	* Gets current machine and the operating system from `uname`
	* Get all raspi-config options
* Network
	* Active interfaces, IP addresses, etc.
* pi-top Software Info
	* Get status of all pi-top systemd services
	* List of pi-top hosted packages and their versions?
* pi-top Hardware Info
	* Reads all values from pi-topHUB, if possible
* Advanced
        * Apt sources

### Later
```
pi-top support {crash_log/forensics/diagnostics/sys_dump}  [--path '/home/pi/Desktop'] [--encrypt] [--upload]
    take optional password for gpg encryption
    attempt to upload to transfer.sh - warn users about security/only allow encrypted?
```

### CODE REVIEW

**Comment by m-roberts** [comment]
Example output:
```
pi@pi-top:~ $ pi-top support health_check
=====================================================================================================================================================
SYSTEM HEALTH CHECK
=====================================================================================================================================================
Current time (GMT): Fri Jan 29 10:55:29 2021

= OS Information ======================================================================================================================================

General Information ---------------------------------------------------------------------------------------------------------------------------------
  └ Kernel Name: Linux
  └ Hostname: pi-top
  └ Kernel Version: 5.4.83-v7l+
  └ Kernel Release: #1379 SMP Mon Dec 14 13:11:54 GMT 2020
  └ Platform: armv7l

pi-topOS Information --------------------------------------------------------------------------------------------------------------------------------
  └ Build Name: Sirius
  └ Build Number: C825
  └ Build Date: 2021-01-12
  └ Build Apt Repo: sirius-unstable
  └ Final Apt Repo: sirius-unstable
  └ Build Pipeline Commit Hash: a715534960573aca70d026c94bc715fe2dd552dd

Content of /etc/issue -------------------------------------------------------------------------------------------------------------------------------
Raspbian GNU/Linux 10 \n \l

= raspi-config Settings ===============================================================================================================================
  └ get_can_expand: 1
  └ get_hostname: pi-top
  └ get_boot_cli: 1
  └ get_autologin: 0
  └ get_boot_wait: 1
  └ get_boot_splash: 0
  └ get_overscan: 1
  └ get_camera: 0
  └ get_ssh: 0
  └ get_vnc: 0
  └ get_spi: 1
  └ get_i2c: 0
  └ get_serial: 1
  └ get_serial_hw: 1
  └ get_onewire: 1
  └ get_rgpio: 1
  └ get_pi_type: 0
  └ get_wifi_country: US

= Network Settings ====================================================================================================================================
Interface: lo -------------------------------------------------------------------------------------------------------------------------------
  └ LINK LAYER: {'addr': '00:00:00:00:00:00', 'peer': '00:00:00:00:00:00'}
  └ IPv4: {'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}
  └ IPv6: {'addr': '::1', 'netmask': 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff'}
Interface: eth0 -----------------------------------------------------------------------------------------------------------------------------
  └ LINK LAYER: {'addr': 'dc:a6:32:b3:53:00', 'broadcast': 'ff:ff:ff:ff:ff:ff'}
Interface: ptusb0 ---------------------------------------------------------------------------------------------------------------------------
  └ LINK LAYER: {'addr': '00:11:22:33:44:55', 'broadcast': 'ff:ff:ff:ff:ff:ff'}
  └ IPv4: {'addr': '192.168.64.1', 'netmask': '255.255.255.0', 'broadcast': '192.168.64.255'}
Interface: wlan0 ----------------------------------------------------------------------------------------------------------------------------
  └ LINK LAYER: {'addr': 'dc:a6:32:b3:53:01', 'broadcast': 'ff:ff:ff:ff:ff:ff'}
  └ IPv4: {'addr': '192.168.1.122', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}
  └ IPv6: {'addr': '2a01:4b00:8a0a:ee00:815:dccf:b8e:bdf9', 'netmask': 'ffff:ffff:ffff:ffff::'}
  └ IPv6: {'addr': 'fd00::ec17:ee8c:a7c1:e7d', 'netmask': 'ffff:ffff:ffff:ffff::'}
  └ IPv6: {'addr': 'fe80::a90c:d1c5:8507:4e5e%wlan0', 'netmask': 'ffff:ffff:ffff:ffff::'}

= pi-top Software Information =========================================================================================================================

pi-top Systemd Services -----------------------------------------------------------------------------------------------------------------------------
  └ pt-coder-bg-catcher.service     loaded static   inactive
  └ pt-device-manager.service       loaded enabled  active
  └ pt-device-registration.service  masked masked   inactive
  └ pt-dhcp-server.service          loaded enabled  active
  └ pt-firmware-updater.service     loaded enabled  active
  └ pt-force-os-update.service      loaded disabled inactive
  └ pt-further-link.service         loaded enabled  active
  └ pt-hotplug-display.service      loaded enabled  active
  └ pt-memory-monitor.service       loaded enabled  active
  └ pt-os-mods.service              loaded enabled  inactive
  └ pt-os-setup.service             loaded disabled inactive
  └ pt-os-updater.service           loaded enabled  inactive
  └ pt-poweroff.service             loaded enabled  inactive
  └ pt-reboot.service               loaded enabled  inactive
  └ pt-sys-oled.service             loaded enabled  failed
  └ pt-version-notify.service       loaded enabled  inactive

pi-top Installed Software ---------------------------------------------------------------------------------------------------------------------------
  └ pt-about v2.0.1
  └ pt-apps v2.1.0
  └ pt-avs v2.0.1
  └ pt-coder v1.0.6
  └ pt-dev v2.1.0
  └ pt-device-manager v4.0.7
  └ pt-devices v2.0.1
  └ pt-eglfs-utils v2.0.0
  └ pt-firmware-images v4.1.0
  └ pt-firmware-updater v3.2.1
  └ pt-further-link v4.0.2
  └ pt-icon-theme v2.0.0
  └ pt-networking v0.3.3
  └ pt-notifications v3.0.0
  └ pt-os v3.0.5
  └ pt-os-archive-keyring v2020.6.15
  └ pt-os-mods v10.0.0
  └ pt-os-setup v3.3.0
  └ pt-os-updater v4.2.8
  └ pt-plym-splash v2.0.0
  └ pt-project-files v1.0.1-1
  └ pt-recovery v1.0.6-1
  └ pt-settings v2.1.1
  └ pt-shutdown-helper v1.0.2-1
  └ pt-sys-oled v3.8.0
  └ pt-system-tools v2.0.0
  └ pt-touchscreen v2.1.0
  └ pt-tour v4.1.0
  └ pt-ui v2.0.0
  └ pt-ui-mods v1.3.20210112
  └ pt-user-libs v3.0.4
  └ pt-web-ui v3.1.0
  └ python3-pitop v0.14.1~15.gbp65debd
  └ python3-pitop-doc v0.13.2
  └ python3-pitop-full v0.14.1~15.gbp65debd
  └ python3-pitop-migr v1:4.0.0
  └ python3-pitopcommon v0.8.0
  └ python3-pt-common v1.20.2-2
  └ python3-pt-speech v2.0.0

APT Sources -----------------------------------------------------------------------------------------------------------------------------------------
  └ http://raspbian.raspberrypi.org/raspbian/ - buster
  └ http://apt.pi-top.com/pi-top-os-internal/ - sirius-unstable
  └ http://apt.pi-top.com/pi-top-os/ - sirius-testing
  └ http://archive.raspberrypi.org/debian/ - buster
  └ http://packages.microsoft.com/repos/code/ - stable

= pi-top Hardware =====================================================================================================================================

Hardware Control and Status -------------------------------------------------------------------------------------------------------------------------
  └ BRD_DETECT: 00000011
  └ MODULE_DETECT: 3
  └ BATT_AND_DISP_I2C_MUX: 0
  └ UI_OLED_CTRL: 00001001
  └ UI_BUTTON_CTRL: 00000000

Diagnostics -----------------------------------------------------------------------------------------------------------------------------------------
  └ UPTIME_STDBY: 62555 mins
  └ UPTIME_RAILSON: 8273 mins
  └ LIFETIME_STDBY: 9226 hours
  └ LIFETIME_RAILSON: 6592 hours
  └ LIFETIME_ONOFFCYC: 352 cycles

Keyboard Control and Status -------------------------------------------------------------------------------------------------------------------------
  └ KEYBOARD_MAC_ADDRESS: 00:00:00:00:00:00
  └ DOCK_FLAG: 0
  └ FW_VER: 0
  └ HW_VER: 0
  └ BT_MASTER_MAC_ADDRESS: 00:00:00:00:00:00
  └ CHRG_THRSH_HUB: 0 %
  └ CHRG_THRSH_KBRD: 0 %
  └ CHARGED_FLAG: 0
  └ BATT_LEVEL: 0 %
  └ PAIRING_STATUS: 0

Advanced Power and Debug ----------------------------------------------------------------------------------------------------------------------------
  └ VOLT_BATT_IN: 8237 mV
  └ VOLT_DC_IN: 11968 mV
  └ VOLT_MPWR_IN: 0 mV
  └ VOLT_VSYS_PRST: 11945 mV
  └ VOLT_5V_PRST: 5181 mV
  └ VOLT_5V: 5150 mV
  └ VOLT_5V_USB: 5119 mV
  └ VOLT_3V3: 3317 mV

Power Controls --------------------------------------------------------------------------------------------------------------------------------------
  └ SHUTDOWN_CTRL: 01000000
  └ BUTT_SHORT_HOLD_TURNON: 0.6  secs
  └ BUTT_SHORT_HOLD_TURNOFF: 1.5  secs
  └ BUTT_LONG_HOLD: 7.0 secs
  └ M1_TIMEOUT_MIN: 0 secs
  └ M1_TIMEOUT_MAX: 300 secs
  └ M2_TIMEOUT_MIN: 0 secs
  └ M2_TIMEOUT_MAX: 120 secs
  └ M3_TIMEOUT: 3 secs
  └ USB_5V_TIMEOUT: 0x001e

Battery Control and Status --------------------------------------------------------------------------------------------------------------------------
  └ STORAGE_MODE: 0
  └ TEMPERATURE: 311.0 K
  └ VOLTAGE: 8237 mV
  └ CURRENT: 0 mA
  └ RSOC: 99 %
  └ TIME_TO_EMPTY: 65535 mins
  └ TIME_TO_FULL: 65535 mins
  └ VOLT_CELL1: 4096 mV
  └ VOLT_CELL2: 4141 mV
  └ VOLT_CELL3: 0 mV
  └ VOLT_CELL4: 0 mV
  └ PF_ERROR: 0
  └ SERIAL_NUM: 1
  └ MANUF_DATE: 2019-11-18
  └ CHARGING_ERROR: 1

Miscellaneous Features ------------------------------------------------------------------------------------------------------------------------------
  └ AUD_CONFIG: 00000000
  └ REAL_TIME_COUNTER: 2019-06-13 10:36:01

Display ---------------------------------------------------------------------------------------------------------------------------------------------
  └ TEST_MODE: 0
  └ BACKLIGHT: 00000000
  └ STATUS: 00000000
  └ MUX_CONTROL: 00000000

Device Information ----------------------------------------------------------------------------------------------------------------------------------
  └ MCU_SOFT_VERS_MAJOR: 5
  └ MCU_SOFT_VERS_MINOR: 4
  └ SCH_REV_MAJOR: 8
  └ SCH_REV_MINOR: 2
  └ BRD_REV: 2
  └ PART_NAME: 0x0607
  └ PART_NUMBER: 0x0001
  └ SERIAL_ID: 0x200006df
  └ DISPLAY_MCU_SOFT_VERS_MAJOR: 1
  └ DISPLAY_MCU_SOFT_VERS_MINOR: 4
  └ DISPLAY_SCH_REV_MAJOR: 0
  └ DISPLAY_SCH_REV_MINOR: 95
  └ DISPLAY_BRD_REV: 0
  └ DISPLAY_PART_NAME: 0x0000
  └ DISPLAY_PART_NUMBER: 0x0000
  └ DISPLAY_SERIAL_ID: 0x0000
pi@pi-top:~ $
```

**Comment by m-roberts** [comment]
#### Overall thoughts
I think we can speed this up (possibly later) by having all sections fetched at the same time (in threads) and printed at once.

I think that this is too long by default. I think that we shouldn't include hardware information unless asked for by the user (possibly with some `--all` parameter?)

#### Formatting changes
##### raspi-config Settings
* parse output to human readable. e.g. `get_can_expand: 1` --> `Filesystem can be expanded? false`

##### Network settings
* Would like to see this as a nested indents (`└`) rather than JSON-like objects that are hard to read

##### pi-top Systemd Services
* include human readable description of each service
* group based on state, hide inactive:
    * active
    * failed

##### pi-top Installed Software
* handle as 'table' (see columns in `pi-top Systemd Services`)
* also include where each package was installed from. example (taken from `apt list` output):
```
python3-pitop-full/now 0.14.1~15.gbp65debd armhf [installed,local]
python3-pitop-migr/sirius-unstable,sirius-testing,now 1:4.0.0 armhf [installed,automatic]
python3-pitop/now 0.14.1~15.gbp65debd armhf [installed,local]
python3-pitopcommon/sirius-unstable,sirius-testing,now 0.8.0 armhf [installed,automatic]
```

**Comment by jcapona** [comment]
```
=================================================================================
SYSTEM HEALTH CHECK
=================================================================================
Current time: Thu, 11 Feb 2021 09:47:59 AM EST

= Raspberry Pi Device Information ===============================================
  └ Device           Raspberry Pi 4 Model B Rev 1.1
  └ Architecture     armv7l
- Raspberry Pi 4 Bootloader Configuration ---------------------------------------
[all]
BOOT_UART=0
WAKE_ON_GPIO=0
POWER_OFF_ON_HALT=1
DHCP_TIMEOUT=45000
DHCP_REQ_TIMEOUT=4000
TFTP_FILE_TIMEOUT=30000
ENABLE_SELF_UPDATE=1
DISABLE_HDMI=0
BOOT_ORDER=0xf41
USB_MSD_PWR_OFF_TIME=1
- Raspberry Pi 4 EEPROM Information ---------------------------------------------
BCM2711 detected
Dedicated VL805 EEPROM detected
BOOTLOADER: up-to-date
CURRENT: Thu 03 Sep 2020 12:11:43 PM UTC (1599135103)
 LATEST: Thu 03 Sep 2020 12:11:43 PM UTC (1599135103)
 FW DIR: /lib/firmware/raspberrypi/bootloader/default
VL805: up-to-date
CURRENT: 000138a1
 LATEST: 000138a1

= System Information ============================================================
  └ Debian Version                                            10.8
  └ Kernel Version                                            5.10.11-v7l+
  └ Kernel Release                                            #1399 SMP Thu Jan 28 12:09:48 GMT 2021
  └ Build Name                                                Sirius
  └ Build Number                                              C781
  └ Build Date                                                2020-12-22
= Interfaces (via raspi-config) =================================================
  └ Camera interface enabled?                                 True
  └ SSH interface enabled?                                    True
  └ VNC interface enabled?                                    True
  └ SPI interface enabled?                                    True
  └ I2C interface enabled?                                    True
  └ Login shell accessible over serial?                       True
  └ Serial interface is enabled?                              True
  └ One-wire interface enabled?                               False
  └ GPIO server to be accessible over the network?            False
= Boot Settings (via raspi-config) ==============================================
  └ Boot to Desktop?                                          True
  └ Autologin?                                                True
  └ Boot waits until a network connection is established?     False
  └ Show splash screen at boot?                               True
= Misc (via raspi-config) =======================================================
  └ Filesystem can be expanded?                               False
  └ Compensation for displays with overscan?                  False

= Network Settings ==============================================================
  └ Hostname         pi-top
  └ WiFi Country     US
- Interface: eth0 ---------------------------------------------------------------
  └ LINK LAYER
    └ addr          dc:a6:32:2f:b2:d7
    └ broadcast     ff:ff:ff:ff:ff:ff
- Interface: ptusb0 -------------------------------------------------------------
  └ LINK LAYER
    └ addr          00:11:22:33:44:55
    └ broadcast     ff:ff:ff:ff:ff:ff
  └ IPv4
    └ addr          192.168.64.1
    └ netmask       255.255.255.0
    └ broadcast     192.168.64.255
  └ IPv6
    └ addr        fe80::3a3:a548:d417:1baa%ptusb0
    └ netmask     ffff:ffff:ffff:ffff::/64
- Interface: wlan0 --------------------------------------------------------------
  └ LINK LAYER
    └ addr          dc:a6:32:2f:b2:db
    └ broadcast     ff:ff:ff:ff:ff:ff
  └ IPv4
    └ addr          192.168.100.33
    └ netmask       255.255.255.0
    └ broadcast     192.168.100.255
  └ IPv6
    └ Subaddress #1
      └ addr        2800:300:6241:70e0::4
      └ netmask     ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/128
    └ Subaddress #2
      └ addr        fe80::7d70:a8d7:617f:a83a%wlan0
      └ netmask     ffff:ffff:ffff:ffff::/64

= pi-top Software Information ===================================================
- pi-top Systemd Services -------------------------------------------------------
  └ active
    └ pt-device-manager (pi-top device auto-detection and configuration daemon)
      └ Loaded: loaded (/lib/systemd/system/pt-device-manager.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:13 EST
    └ pt-dhcp-server (pi-topOS DHCP server)
      └ Loaded: loaded (/lib/systemd/system/pt-dhcp-server.service; enabled; vendor preset: enabled)
      └ Active: active (exited) since Thu 2021-02-11 08:24:10 EST
    └ pt-firmware-updater (pi-top device firmware updater daemon)
      └ Loaded: loaded (/lib/systemd/system/pt-firmware-updater.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:13 EST
    └ pt-further-link (pi-top Further Link)
      └ Loaded: loaded (/lib/systemd/system/pt-further-link.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:11 EST
    └ pt-hotplug-display (pi-top [4] touchscreen hotplug service)
      └ Loaded: loaded (/lib/systemd/system/pt-hotplug-display.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:10 EST
    └ pt-memory-monitor (pi-top memory monitor)
      └ Loaded: loaded (/lib/systemd/system/pt-memory-monitor.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:10 EST
    └ pt-sys-oled (pi-top OLED system menu)
      └ Loaded: loaded (/lib/systemd/system/pt-sys-oled.service; enabled; vendor preset: enabled)
      └ Active: active (running) since Thu 2021-02-11 08:24:13 EST
  └ inactive
    └ pt-coder-bg-catcher (background input catcher for pi-topCODER)
      └ Loaded: loaded (/lib/systemd/system/pt-coder-bg-catcher.service; static; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-device-registration (pt-device-registration.service)
      └ Loaded: masked
      └ Active: inactive (dead)
    └ pt-force-os-update (pi-topOS updater service)
      └ Loaded: loaded (/lib/systemd/system/pt-force-os-update.service; disabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-os-mods (pi-topOS system modifications service)
      └ Loaded: loaded (/lib/systemd/system/pt-os-mods.service; enabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-os-setup (pi-topOS Onboarding Web Server)
      └ Loaded: loaded (/lib/systemd/system/pt-os-setup.service; disabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-os-updater (pi-topOS updater service)
      └ Loaded: loaded (/lib/systemd/system/pt-os-updater.service; enabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-poweroff (pi-topHUB shutdown announcement)
      └ Loaded: loaded (/lib/systemd/system/pt-poweroff.service; enabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-reboot (pi-top[4] reboot announcement)
      └ Loaded: loaded (/lib/systemd/system/pt-reboot.service; enabled; vendor preset: enabled)
      └ Active: inactive (dead)
    └ pt-version-notify (pi-topOS version warning)
      └ Loaded: loaded (/lib/systemd/system/pt-version-notify.service; enabled; vendor preset: enabled)
      └ Active: inactive (dead)
- pi-top Installed Software -----------------------------------------------------
  └ pt-about                  2.0.1
  └ pt-apps                   2.2.0
  └ pt-avs                    2.0.1
  └ pt-coder                  1.0.6
  └ pt-dev                    2.1.0
  └ pt-device-manager         4.1.0
  └ pt-devices                2.0.1
  └ pt-eglfs-utils            2.0.0
  └ pt-firmware-images        4.1.0
  └ pt-firmware-updater       3.2.1
  └ pt-further-link           4.2.1
  └ pt-icon-theme             2.0.0
  └ pt-networking             0.3.3
  └ pt-notifications          3.0.0
  └ pt-os                     3.0.5
  └ pt-os-archive-keyring     2020.6.15
  └ pt-os-mods                10.0.0
  └ pt-os-setup               3.3.0
  └ pt-os-updater             4.2.8
  └ pt-plym-splash            2.0.0
  └ pt-project-files          1.0.1-1
  └ pt-recovery               1.0.6-1
  └ pt-settings               2.1.1
  └ pt-shutdown-helper        1.0.2-1
  └ pt-sys-oled               4.1.0
  └ pt-system-tools           2.0.0
  └ pt-touchscreen            2.1.0
  └ pt-tour                   4.1.0
  └ pt-ui                     2.0.0
  └ pt-ui-mods                1.3.20210211
  └ pt-user-libs              3.0.4
  └ pt-web-ui                 3.1.0
  └ python3-pitop             0.16.1
  └ python3-pitop-doc         0.16.1
  └ python3-pitop-full        0.16.1
  └ python3-pitop-migr        1:4.0.0
  └ python3-pitopcommon       0.8.0
  └ python3-pt-common         1.20.2-2
  └ python3-pt-speech         2.0.0
- APT Sources -------------------------------------------------------------------
  └ /etc/apt/sources.list
    └ deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
  └ /etc/apt/sources.list.d/raspi.list
    └ deb http://archive.raspberrypi.org/debian/ buster main
  └ /etc/apt/sources.list.d/vscode.list
    └ deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
  └ /etc/apt/sources.list.d/pi-top.list
    └ deb http://apt.pi-top.com/pi-top-os/ sirius-testing main contrib non-free
    └ deb http://apt.pi-top.com/pi-top-os-internal/ sirius-unstable main contrib non-free

= pi-top Device Information =====================================================
- Hardware Control and Status ---------------------------------------------------
  └ BRD_DETECT                      00000011
  └ MODULE_DETECT                   3
  └ BATT_AND_DISP_I2C_MUX           0
  └ UI_OLED_CTRL                    00000101
  └ UI_BUTTON_CTRL                  00000000
- Diagnostics -------------------------------------------------------------------
  └ UPTIME_STDBY                    17111 min
  └ UPTIME_RAILSON                  83 min
  └ LIFETIME_STDBY                  7928 hour
  └ LIFETIME_RAILSON                3257 hour
  └ LIFETIME_ONOFFCYC               808 cycle
- Keyboard Cotnrol and Status ---------------------------------------------------
  └ KEYBOARD_MAC_ADDRESS            00:00:00:00:00:00
  └ DOCK_FLAG                       0
  └ FW_VER                          0
  └ HW_VER                          0
  └ BT_MASTER_MAC_ADDRESS           00:00:00:00:00:00
  └ CHRG_THRSH_HUB                  0
  └ CHRG_THRSH_KBRD                 0
  └ CHARGED_FLAG                    0
  └ BATT_LEVEL                      0
  └ PAIRING_STATUS                  0
- Advanced Power and Debug ------------------------------------------------------
  └ VOLT_BATT_IN                    8220 mV
  └ VOLT_DC_IN                      12046 mV
  └ VOLT_MPWR_IN                    0 mV
  └ VOLT_VSYS_PRST                  11964 mV
  └ VOLT_5V_PRST                    5150 mV
  └ VOLT_5V                         5150 mV
  └ VOLT_5V_USB                     5085 mV
  └ VOLT_3V3                        3338 mV
- Power Controls ----------------------------------------------------------------
  └ SHUTDOWN_CTRL                   01000000
  └ BUTT_SHORT_HOLD_TURNON          0.6 sec
  └ BUTT_SHORT_HOLD_TURNOFF         1.5 sec sec
  └ BUTT_LONG_HOLD                  7.0 sec sec
  └ M1_TIMEOUT_MIN                  0 sec
  └ M1_TIMEOUT_MAX                  300 sec
  └ M2_TIMEOUT_MIN                  0 sec
  └ M2_TIMEOUT_MAX                  120 sec
  └ M3_TIMEOUT                      3 sec
  └ USB_5V_TIMEOUT                  0x001e
- Battery Control and Status ----------------------------------------------------
  └ STORAGE_MODE                    0
  └ TEMPERATURE                     308.7 K
  └ VOLTAGE                         8220 mV
  └ CURRENT                         0 mA
  └ RSOC                            97 %
  └ TIME_TO_EMPTY                   65535 mins
  └ TIME_TO_FULL                    65535 mins
  └ VOLT_CELL1                      4112 mV
  └ VOLT_CELL2                      4110 mV
  └ VOLT_CELL3                      0 mV
  └ VOLT_CELL4                      0 mV
  └ PF_ERROR                        0
  └ SERIAL_NUM                      1
  └ MANUF_DATE                      2019-10-25
  └ CHARGING_ERROR                  1
- Miscellaneous Features --------------------------------------------------------
  └ AUD_CONFIG                      00000000
  └ REAL_TIME_COUNTER               2019-05-12 21:11:10
- Display -----------------------------------------------------------------------
  └ TEST_MODE                       0
  └ BACKLIGHT                       00000000
  └ STATUS                          00000000
  └ MUX_CONTROL                     00000000
- Device Information ------------------------------------------------------------
  └ MCU_SOFT_VERS_MAJOR             5
  └ MCU_SOFT_VERS_MINOR             4
  └ SCH_REV_MAJOR                   8
  └ SCH_REV_MINOR                   2
  └ BRD_REV                         2
  └ PART_NAME                       0x0607
  └ PART_NUMBER                     0x0001
  └ SERIAL_ID                       0x20000070
  └ DISPLAY_MCU_SOFT_VERS_MAJOR     1
  └ DISPLAY_MCU_SOFT_VERS_MINOR     4
  └ DISPLAY_SCH_REV_MAJOR           0
  └ DISPLAY_SCH_REV_MINOR           95
  └ DISPLAY_BRD_REV                 0
  └ DISPLAY_PART_NAME               0x0000
  └ DISPLAY_PART_NUMBER             0x0000
  └ DISPLAY_SERIAL_ID               0x0000
```

**Review by jcapona — APPROVED** [review]
great job!

**Comment by m-roberts** [comment]
Cheers buddy

**Pull request merged**
